hmcts/darts-gateway

infrastructure/apim.tf

Using APIM in sandbox for testing

---

infrastructure/apim.tf

Reverts hmcts/darts-gateway#18

Revert "Using APIM in sandbox for testing"

---

Jenkinsfile_CNP

Sandbox env

---

src/main/resources/dartsService.wsdl

Adding DARTS WSDL

---

Jenkinsfile_CNP
infrastructure/apim.tf

Using DartsService WSDL in APIM terraform

---

infrastructure/apim.tf
infrastructure/main.tf

- attempting to allow access from APIM to AKS
```
[ ] Yes
[ ] No
```

Tweaking terraform providers

---

infrastructure/apim-policy/api-policy.xml
infrastructure/apim.tf
infrastructure/demo.tfvars
infrastructure/sbox.tfvars
infrastructure/stg.tfvars
infrastructure/variables.tf

- using ingress IP address for APIM backend
- setting HOST header as hostname for API
```
[ ] Yes
[ ] No
```

Config updates for APIM to AKS

---

config/owasp/suppressions.xml
infrastructure/prod.tfvars

Prod tfvars and suppress CVE

---

charts/darts-gateway/Chart.yaml
charts/darts-gateway/values.yaml
infrastructure/apim-policy/api-policy.xml
infrastructure/apim.tf
infrastructure/demo.tfvars
infrastructure/prod.tfvars
infrastructure/sbox.tfvars
infrastructure/stg.tfvars
infrastructure/variables.tf

- updating default ingress host
- replacing loadbalancer IP as APIM backend with hostname
- no need to template the api-policy file anymore
```
[ ] Yes
[ ] No
```

Updating APIM to work with hostnames

---

src/main/java/uk/gov/hmcts/darts/common/client/DartsFeignClient.java

DMP-464: Fixing feign client headers

---

src/main/java/uk/gov/hmcts/darts/common/util/DateConverters.java
src/main/java/uk/gov/hmcts/darts/courtlogs/GetCourtLogsMapper.java
src/test/java/uk/gov/hmcts/darts/common/util/DateConvertersTest.java
src/test/java/uk/gov/hmcts/darts/courtlogs/GetCourtLogsMapperTest.java
src/test/java/uk/gov/hmcts/darts/utilities/assertions/CourtLogAssert.java
src/test/java/uk/gov/hmcts/darts/utilities/assertions/CustomAssertions.java
src/test/java/uk/gov/hmcts/darts/utilities/assetions/CourtLogAssert.java

DMP-751: fixing timezone issue

---

src/integrationTest/java/uk/gov/hmcts/darts/utils/DailyListApiStub.java
src/main/java/uk/gov/hmcts/darts/common/client/DartsFeignClient.java
src/main/java/uk/gov/hmcts/darts/config/FeignConfig.java
src/main/java/uk/gov/hmcts/darts/dailylist/DailyListRoute.java
src/main/java/uk/gov/hmcts/darts/dailylist/mapper/DailyListRequestMapper.java
src/main/java/uk/gov/hmcts/darts/dailylist/mapper/DailyListXmlRequestMapper.java
src/main/java/uk/gov/hmcts/darts/dailylist/model/PostDailyListRequest.java
src/main/java/uk/gov/hmcts/darts/ws/DartsEndpoint.java
src/main/resources/application.yaml
src/main/resources/openapi/cases.yaml
src/main/resources/openapi/dailylist.yaml
src/test/java/uk/gov/hmcts/darts/dailylist/mapper/DailyListRequestMapperTest.java

https://tools.hmcts.net/jira/browse/DMP-657
Change gateway functionality to call the new 2-step dailyList endpoints so that XML would be saved first in case of a problem with the JSON.

Dmp 657.add document2

---

src/integrationTest/java/uk/gov/hmcts/darts/utils/client/DartsGatewayClient.java
src/integrationTest/java/uk/gov/hmcts/darts/utils/client/DartsGatewayMtomClient.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/AddAudioWebServiceTest.java
src/integrationTest/resources/payloads/addAudio/expectedResponse.xml
src/integrationTest/resources/payloads/addAudio/soapRequest.xml
src/main/java/uk/gov/hmcts/darts/addaudio/AddAudioRoute.java
src/main/java/uk/gov/hmcts/darts/ws/DartsEndpoint.java
src/main/java/uk/gov/hmcts/darts/ws/ResponseFactory.java

addAudio stub added

---

README.md
charts/darts-gateway/Chart.yaml
charts/darts-gateway/values.dev.template.yaml
charts/darts-gateway/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-1297
Added spaces just to force a refresh of azure settings
```
[ ] Yes
[x ] No
```

DMP-1297-AddAuthorisationForXHIBITCPP

---

build.gradle
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-1639
Need to get up to date
```
[ ] Yes
[x] No
```

dmp 1639 dummy change to run build

---

src/integrationTest/java/uk/gov/hmcts/darts/ws/AddAudioWebServiceTest.java
src/integrationTest/resources/payloads/addAudio/register/problemResponse.json
src/integrationTest/resources/payloads/addAudio/register/problemResponse.xml
src/integrationTest/resources/payloads/addAudio/register/soapRequestEmptyCourthouse.xml
src/integrationTest/resources/payloads/addAudio/register/soapRequestUnknownCourthouse.xml
src/main/java/uk/gov/hmcts/darts/addaudio/AddAudioRoute.java
src/main/java/uk/gov/hmcts/darts/addaudio/validator/AddAudioValidator.java
src/main/java/uk/gov/hmcts/darts/common/client/exeption/addaudio/AudioAPIAddAudioException.java
src/main/java/uk/gov/hmcts/darts/common/client/mapper/AudioAPIProblemResponseMapper.java
src/main/java/uk/gov/hmcts/darts/config/ServiceConfig.java
src/test/java/uk/gov/hmcts/darts/common/client/mapper/AudioAPIErrorResponseMapperTest.java

https://tools.hmcts.net/jira/browse/DMP-1937
```
[ ] Yes
[x] No
```

dmp 1937 Added error handling

---

src/main/java/uk/gov/hmcts/darts/dailylist/DailyListRoute.java

N/A
- send JSON string in patch only
- only attempt to marshal into JSON after sending the post and saving the XML
```
[ ] Yes
[X] No
```

Daily list fix

---

Jenkinsfile_CNP

DMP-1875-ITHC-Test

---

src/main/java/uk/gov/hmcts/darts/addaudio/validator/AddAudioValidator.java

https://tools.hmcts.net/jira/browse/DMP-1937
```
[ ] Yes
[x] No
```

dmp-1937 fix null problem

---

src/integrationTest/java/uk/gov/hmcts/darts/utils/EventApiStub.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/EventWebServiceTest.java
src/integrationTest/resources/payloads/events/valid-event-api-request.json
src/integrationTest/resources/payloads/events/valid-event.xml
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventRequestMapper.java
src/test/java/uk/gov/hmcts/darts/event/service/impl/EventRequestMapperTest.java

https://tools.hmcts.net/jira/browse/DMP-2163
- adding unit test
- amending the integration test to assert the whole request body
```
[ ] Yes
[X] No
```

DMP-2163 Adding "event_id" to the event DARTS API POST request

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
README.md
bin/secrets-stg.sh
charts/darts-gateway/Chart.yaml
charts/darts-gateway/values.dev.template.yaml
charts/darts-gateway/values.yaml
docker-compose-local.yml
docker-compose.yml

https://tools.hmcts.net/jira/browse/DMP-2232
Use new Azure Scope in Darts Gateway
```
[ ] Yes
[X] No
```

DMP-2232 Updated resources with AAD_B2C_CLIENT_ID_KEY

---

build.gradle
src/main/java/uk/gov/hmcts/darts/event/client/DarNotifyEventClient.java
src/main/java/uk/gov/hmcts/darts/event/config/DarNotifyEventConfiguration.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventRequestMapper.java
src/main/java/uk/gov/hmcts/darts/log/api/LogApi.java
src/main/java/uk/gov/hmcts/darts/log/api/impl/LogApiImpl.java
src/main/java/uk/gov/hmcts/darts/log/service/DarNotificationLoggerService.java
src/main/java/uk/gov/hmcts/darts/log/service/impl/DarNotificationLoggerServiceImpl.java
src/test/java/uk/gov/hmcts/darts/event/client/DarNotifyEventClientTest.java
src/test/java/uk/gov/hmcts/darts/log/service/impl/DarNotificationLoggerServiceImplTest.java

Logging dar pc notifications
```
[ ] Yes
[x] No
```

Logging dar pc notifications

---

README.md
charts/darts-gateway/Chart.yaml
charts/darts-gateway/values.yaml
docker-compose-local.yml
docker-compose.yml
src/integrationTest/java/uk/gov/hmcts/darts/event/controller/DarNotifyControllerTest.java
src/main/java/uk/gov/hmcts/darts/event/client/DarNotifyEventClient.java
src/main/java/uk/gov/hmcts/darts/event/config/DarNotifyEventConfiguration.java
src/main/java/uk/gov/hmcts/darts/event/config/DarNotifyEventConfigurationProperties.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyEventServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/event/client/DarNotifyEventClientTest.java

Removing default url for dar pc prop tidy
```
[ ] Yes
[x] No
```

Removing default url for dar pc prop tidy

---

src/main/resources/application.yaml

Added request/response logging at trace level
```
[ ] Yes
[x] No
```

DMP-2491: Added request/response logging at trace level

---

src/main/java/uk/gov/hmcts/darts/ws/DartsEndpoint.java
src/main/resources/application.yaml

Added temporary logging
```
[ ] Yes
[x] No
```

DMP-2491: Added temporary logging

---

src/integrationTest/resources/payloads/soapHeaderSecurityToken.xml
src/main/java/uk/gov/hmcts/darts/authentication/component/SoapRequestInterceptor.java

https://tools.hmcts.net/jira/browse/DMP-2496
Change to support authentication prioritising using the token block in the soap header 
```
[ ] Yes
[x] No - Hopefully this corrects the breaking change
```

DMP-2496: Prioritise Token SOAP header

---

src/main/resources/application.yaml

N/A
As title
```
[ ] Yes
[x] No
```

Fixing redis namespace used for session

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/DisablingDarPcNotificationTest.java
src/integrationTest/java/uk/gov/hmcts/darts/utils/DarPcStub.java
src/main/java/uk/gov/hmcts/darts/event/client/DarNotifyEventClient.java
src/main/java/uk/gov/hmcts/darts/event/config/DarNotifyEventConfiguration.java
src/main/java/uk/gov/hmcts/darts/event/enums/DarNotifyEventResult.java
src/test/java/uk/gov/hmcts/darts/event/enums/DarNotifyEventResultTest.java

Updating integration tests for Dar Pc notifications and a few other small tidy ups 
```
[ ] Yes
[x] No
```

DMP-1608-dar-pc-int-test

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-2607
Dynamic attributes for Azure AD B2C
```
[ ] Yes
[x] No
```

dmp-2607:dynamic-azure-b2c-attributes

---

Jenkinsfile_CNP
charts/darts-gateway/Chart.yaml
charts/darts-gateway/values.yaml

DMP-2610
Dynamic Azure B2C Attributes
```
[ ] Yes
[ ] No
```

dmp-2610:dynamic-azure-b2c-attributes

---

charts/darts-gateway/Chart.yaml
charts/darts-gateway/values.yaml
src/main/resources/application.yaml

DMP-2613
Azure AD B2C dynamic attributes
```
[ ] Yes
[x] No
```

dmp-2613:dynamic-azure-b2c-attributes

---

src/integrationTest/java/uk/gov/hmcts/darts/utils/AuthenticationAssertion.java
src/main/java/uk/gov/hmcts/darts/common/exceptions/soap/documentum/ServiceExceptionType.java

Remove message args

---

src/integrationTest/java/uk/gov/hmcts/darts/utils/DailyListApiStub.java
src/integrationTest/resources/payloads/events/valid-dailyList-with-line-breaks.xml
src/main/java/uk/gov/hmcts/darts/dailylist/DailyListRoute.java
src/main/java/uk/gov/hmcts/darts/routing/EventRoutingService.java

https://tools.hmcts.net/jira/browse/DMP-2609
Sending message id on daily lists
```
[ ] Yes
[x] No
```

DMP-2609: Sending message id on daily lists

---

src/integrationTest/resources/payloads/getCases/soapRequest.xml
src/main/java/uk/gov/hmcts/darts/cases/impl/CasesRouteImpl.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/GetCasesMapper.java
src/main/java/uk/gov/hmcts/darts/utilities/DateUtil.java

fix date parsing issue seen in model court.

---

src/integrationTest/resources/payloads/getCases/expectedResponse.xml
src/main/java/uk/gov/hmcts/darts/cases/mapper/GetCasesMapper.java
src/main/java/uk/gov/hmcts/darts/utilities/DartsResponseUtil.java
src/test/resources/tests/cases/GetCasesMapperTest/mapOk/expectedResponse.json

fix getCases message and code

---

src/integrationTest/resources/payloads/getCases/expectedResponse.xml
src/main/java/uk/gov/hmcts/darts/cases/impl/CasesRouteImpl.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/GetCasesMapper.java
src/test/java/uk/gov/hmcts/darts/cases/mapper/GetCasesMapperTest.java
src/test/resources/tests/cases/GetCasesMapperTest/mapOk/expectedResponse.json

fix getCases Response - remove case attributes.

---

src/integrationTest/resources/payloads/events/valid-event-api-request.json
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventRequestMapper.java
src/main/java/uk/gov/hmcts/darts/utilities/DateUtil.java
src/test/java/uk/gov/hmcts/darts/event/service/impl/EventRequestMapperTest.java

Fix eventTimes as they are an hour out.

---

src/main/java/uk/gov/hmcts/darts/cases/mapper/AddCaseMapper.java

https://tools.hmcts.net/jira/browse/DMP-2869

DMP-2869 - change to add case to not create a hearing

---

src/main/java/uk/gov/hmcts/darts/event/client/DarNotifyEventClient.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-2938
Adding logging of SOAP message for testing
```
[ ] Yes
[x] No
```

DMP-2938: Adding logging of SOAP message for testing

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/DarNotifyControllerTest.java
src/main/resources/schemas/internal-dar-notify-event.xsd

Fix for the case of the 'Event' element in the DAR PC notification request.

fix case of 'Event' in the DAR PC notification request

---

build.gradle
src/main/java/uk/gov/hmcts/darts/event/config/DarNotifyEventConfiguration.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyEventServiceImpl.java
src/main/resources/schemas/dar-notify-event.xsd
src/main/resources/schemas/event.xsd
src/test/java/uk/gov/hmcts/darts/event/client/DarNotifyEventClientTest.java

Tidying after pushing through fix for https://tools.hmcts.net/jira/browse/DMP-2948
```
[ ] Yes
[x] No
```

DMP-2948: Tidying after pushing through fix

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/darts/workflow/command/AddAudioMidTierCommand.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/AddAudioWebServiceTest.java
src/integrationTest/resources/addaudio/badsignature.mp2
src/integrationTest/resources/application-int-test.yaml
src/integrationTest/resources/payloads/addAudio/register/problemResponse500.json
src/integrationTest/resources/payloads/addAudio/register/soapRequestDurationExceeded.xml
src/integrationTest/resources/payloads/addAudio/register/soapRequestInvalidExtension.xml
src/main/java/uk/gov/hmcts/darts/addaudio/AddAudioRoute.java
src/main/java/uk/gov/hmcts/darts/addaudio/validator/AddAudioFileValidator.java
src/main/java/uk/gov/hmcts/darts/addaudio/validator/AddAudioValidator.java
src/main/java/uk/gov/hmcts/darts/common/util/Validator.java
src/main/java/uk/gov/hmcts/darts/config/AllowedMediaConfig.java
src/main/java/uk/gov/hmcts/darts/utilities/MapperUtility.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-3011
DARTS Gateway - pre-validation of audio files
```
[ ] Yes
[X] No
```

DMP-3011 Pre-validate audio

---

src/main/java/uk/gov/hmcts/darts/addaudio/validator/AddAudioValidator.java

https://tools.hmcts.net/jira/browse/DMP-3011
This is to fix bug reported for AC1
```
[ ] Yes
[X] No
```

DMP-3011 Fixed AC1

---

src/main/java/uk/gov/hmcts/darts/common/client/mapper/ProblemResponseMapping.java
src/test/java/uk/gov/hmcts/darts/common/client/mapper/APIResponseMapperTest.java

https://tools.hmcts.net/jira/browse/DMP-2973

DMP-2973 - Handle a Problem without a Type.

---

src/integrationTest/java/uk/gov/hmcts/darts/utils/DailyListApiStub.java
src/main/java/uk/gov/hmcts/darts/dailylist/mapper/DailyListXmlRequestMapper.java
src/test/resources/tests/dailylist/DailyListXmlRequestMapperTest/publishedDateGmtWithTimeZone.xml
src/test/resources/tests/dailylist/DailyListXmlRequestMapperTest/publishedDateGmtWithoutTimeZone.xml

https://tools.hmcts.net/jira/browse/DMP-3086

DMP-3086 - Change DailyList mapper to use timestamp as published time

---

src/main/resources/application.yaml

Amending token idle time to 4 hours, to match token expiry

---

src/integrationTest/java/uk/gov/hmcts/darts/utils/DailyListApiStub.java
src/main/java/uk/gov/hmcts/darts/dailylist/DailyListRoute.java
src/test/resources/tests/dailylist/DailyListRequestMapperTest/test1/expectedResponse.json
src/test/resources/tests/dailylist/DailyListRequestMapperTest/test1/request.xml

Step 4 of 5 - repoint gateway to original dailyList endpoint
https://tools.hmcts.net/jira/browse/DMP-3209

DMP-3209  - repoint dailylist route to v1 endpoint

---

charts/darts-gateway/Chart.yaml
charts/darts-gateway/values.dev.template.yaml
charts/darts-gateway/values.stg.template.yaml

https://tools.hmcts.net/jira/browse/DMP-3357
Helm chart changes to functional tests
```
[ ] Yes
[x] No
```

DMP-3357: Helm chart changes to support functional testing

---

src/integrationTest/java/uk/gov/hmcts/darts/test/TestSupportControllerTest.java
src/integrationTest/java/uk/gov/hmcts/darts/workflow/AddAudioMtomMidTierWorkflowTest.java
src/integrationTest/java/uk/gov/hmcts/darts/workflow/command/DeployRedisCommand.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/AddAudioWebServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/BasicAuthorisationTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/CasesWebServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/ContextRegistryDocumentumToJwtServiceSharedTokenTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/ContextRegistryDocumentumToJwtServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/ContextRegistryJwtServiceSharedTokenTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/ContextRegistryJwtServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/CourtLogsWebServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/EventWebServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/RegisterNodeWebServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/ws/WsdlTest.java

Fixing redis image for test containers and re-enabling tests

---

src/main/resources/application.yaml

DMP-3356
Increased the Cache Expiry time
```
[ ] Yes
[ ] No
```

dmp-3356: increase Cache expiry time

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/swagger.yml
Dockerfile
README.md
build.gradle
context/build.gradle

https://tools.hmcts.net/jira/browse/DMP-1557
Upgrade Java version to 21
```
[ ] Yes
[x ] No
```

DMP-1557 Upgrade Java version to 21

---

src/integrationTest/resources/application-int-test.yaml
src/main/java/uk/gov/hmcts/darts/addaudio/validator/AddAudioFileValidator.java
src/main/java/uk/gov/hmcts/darts/config/AllowedMediaConfig.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-3256

Dmp 3256.add allowed media extensions

---

src/main/resources/application.yaml
src/main/resources/logback-spring.xml

Using an async logging appender and moving all logging config to a spring logback config file
https://tools.hmcts.net/jira/browse/DMP-3603
```
[ ] Yes
[x] No
```

DMP-3603-async-logging

---

src/main/java/uk/gov/hmcts/darts/common/exceptions/DartsSoapFaultDefinitionExceptionResolver.java

N/A
Revert the response from server fault code back to client fault code
```
[ ] Yes
[ ] No
```

NOJIRA: Change response fault code to client from server

---

src/integrationTest/java/uk/gov/hmcts/darts/ws/CasesWebServiceTest.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/AddCaseMapper.java
src/test/java/uk/gov/hmcts/darts/cases/mapper/AddCaseMapperTest.java

Dmp 3007.case type

---

src/main/java/uk/gov/hmcts/darts/authentication/component/SoapRequestInterceptor.java
src/test/java/uk/gov/hmcts/darts/authentication/component/SoapRequestInterceptorTest.java

https://tools.hmcts.net/jira/browse/DMP-3931
Log the cookie lifecycle scenarios:-
Allocation of new session due to a session not being found on the server
Allocation of new sesion due to client not sending the session id
Use of existing server token due to a match being found
```
[ ] Yes
[x] No
```

DMP-3931: Add cookie header log

---

.github/renovate.json
.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
docker-compose-local-to-staging.yml
src/functionalTest/java/uk/gov/hmcts/darts/ContextRegistryPerformanceTest.java
src/functionalTest/java/uk/gov/hmcts/darts/ContextRegistryTest.java
src/main/java/uk/gov/hmcts/darts/authentication/component/SoapRequestInterceptor.java
src/test/java/uk/gov/hmcts/darts/authentication/component/SoapRequestInterceptorTest.java

https://tools.hmcts.net/jira/browse/DMP-3950

DMP-3950 - fix cookie JSessionId issue

---

charts/darts-gateway/Chart.yaml
charts/darts-gateway/values.yaml

https://tools.hmcts.net/jira/browse/DMP-3602
Change to use environment variables instead of secrets for the jkws refresh values
```
[ ] Yes
[x] No
```

DMP-3602: Change to use environment variables

---

CODEOWNERS

Try this @Jack

---

.github/CODEOWNERS

This one needs changing too @Jack

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/darts/testutils/MemoryLogAppender.java
src/main/java/uk/gov/hmcts/darts/authentication/component/SoapRequestInterceptor.java
src/main/java/uk/gov/hmcts/darts/cache/token/component/impl/TokenValidatorImpl.java
src/main/java/uk/gov/hmcts/darts/log/conf/LogProperties.java
src/test/java/uk/gov/hmcts/darts/log/service/impl/DarNotificationLoggerServiceImplTest.java
src/testCommon/java/uk.gov.hmcts.darts.common.utils/client/ctxt/ContextRegistryClientProvider.java
src/testCommon/java/uk.gov.hmcts.darts.common.utils/client/ctxt/ContextRegistryXmlClient.java
src/testCommon/java/uk.gov.hmcts.darts.common.utils/client/darts/DartsGatewayMtomClient.java
src/testCommon/java/uk.gov.hmcts.darts.common.utils/client/darts/DartsGatewayXmlClient.java

Dependency update

---

DARTS-Gateway.postman_collection.json

Add postman collection to aid testing.

add postman collection

---

src/main/java/uk/gov/hmcts/darts/addaudio/AddAudioRoute.java
src/main/resources/application.yaml

Temp change to force checksum failure on upload

Temp change to force checksum failure on upload

---

src/main/java/uk/gov/hmcts/darts/log/api/impl/LogApiImpl.java
src/test/java/uk/gov/hmcts/darts/log/service/impl/LogApiImplTest.java

Fixed logging message

---

src/main/java/uk/gov/hmcts/darts/addaudio/validator/AddAudioFileValidator.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4808)
The recent changes made to the `AddAudioFileValidator.java` file enhance logging for invalid audio file extensions during validation. The log message now includes the actual extension received and the list of expected extensions.
- **Enhanced Logging**: The log message for invalid file extensions now includes:
- The actual extension provided (`extension`).
- The list of expected extensions from `allowedMediaConfig`.
- **Exception Handling**: The code continues to throw a `DartsValidationException` when the extension is not valid, ensuring consistent error management.
```
[ ] Yes
[X] No
```

DMP-4808: Improve add audio file validation logging

---

src/integrationTest/java/uk/gov/hmcts/darts/workflow/command/AddAudioMidTierCommand.java

N/A
- to prevent docker hub rate limiting issues
```
[ ] Yes
[ ] No
```

Using the williamyeh/java8 image from ACR

---

charts/darts-gateway/Chart.yaml

N/A
- some versions are becoming deprecated soon
```
[ ] Yes
[ ] No
```

Updating helm charts

---

src/main/resources/application.yaml

Fixing use of `darts-gateway.security.sign-in-policy` in app config

---

src/integrationTest/resources/payloads/events/valid-case-api.json
src/main/java/uk/gov/hmcts/darts/cases/impl/CaseInfoRouteImpl.java
src/test/java/uk/gov/hmcts/darts/cases/impl/CaseInfoRouteImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4752
https://tools.hmcts.net/jira/browse/DMP-4753
NEWCASE and UPDCASE was incorrectly setting defenders, fixing this to set defendants
```
[ ] Yes
[ ] No
```

DMP-4752 DMP-4753 NEWCASE/UPDCASE should set defendants, not defenders

---

lib/applicationinsights.json
src/main/java/uk/gov/hmcts/darts/authentication/component/SoapRequestInterceptor.java
src/main/java/uk/gov/hmcts/darts/cache/token/component/impl/TokenValidatorImpl.java
src/main/resources/application.yaml

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4952)
This Git diff shows a modification to the `applicationinsights.json` file, specifically adding a new section for Redis instrumentation settings.
- Added an `"instrumentation"` section to the JSON file.
- Introduced a `"redis"` configuration within the `"instrumentation"` section.
- Set the `"enabled"` property for Redis instrumentation to `false`.
```
[ ] Yes
[X] No
```

DMP-4952: Remove JWT logging from services

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java
src/integrationTest/resources/payloads/events/invalidPayloadResponse.xml
src/main/java/uk/gov/hmcts/darts/addaudio/AddAudioRoute.java
src/main/java/uk/gov/hmcts/darts/cache/token/component/TokenGenerator.java
src/main/java/uk/gov/hmcts/darts/cache/token/component/TokenValidator.java
src/main/java/uk/gov/hmcts/darts/cases/CaseInfoRoute.java
src/main/java/uk/gov/hmcts/darts/common/client/CourthousesClient.java
src/main/java/uk/gov/hmcts/darts/common/client/EventsClient.java
src/main/java/uk/gov/hmcts/darts/common/client/RegisterNodeClient.java
src/main/java/uk/gov/hmcts/darts/common/client/exeption/ClientProblemException.java
src/main/java/uk/gov/hmcts/darts/common/client/exeption/DartsClientProblemDecoder.java
src/main/java/uk/gov/hmcts/darts/common/client/mapper/DailyListAPIProblemResponseMapper.java
src/main/java/uk/gov/hmcts/darts/common/client/mapper/EventAPIProblemResponseMapper.java
src/main/java/uk/gov/hmcts/darts/common/exceptions/DartsException.java
src/main/java/uk/gov/hmcts/darts/common/multipart/XmlAndFileUploadRequestFactory.java
src/main/java/uk/gov/hmcts/darts/common/util/Validator.java
src/main/java/uk/gov/hmcts/darts/event/service/DarNotifyEventService.java
src/test/java/uk/gov/hmcts/darts/common/client/mapper/DailyListAPIErrorResponseMapperTest.java
src/test/java/uk/gov/hmcts/darts/common/client/mapper/EventAPIErrorResponseMapperTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4792)
This Git diff reflects several modifications across multiple files in a Java project. The most significant changes include updates to dependency management in the build configuration, various optimizations in integration test utilities, and the introduction of `@FunctionalInterface` annotations to several interfaces. Additionally, certain classes and methods have been modified to enhance readability and functionality.
- **Build Configuration Enhancements**:
- Added `jacocoTestReport.dependsOn check` to ensure coverage reports are generated post-check.
- **Integration Test Improvements**:
- Simplified the structure of `IntegrationBase.java` by removing unused imports and methods.
- Updated annotations to streamline test configurations. …

DMP-4792: (Dev only) Improve the error message when 'Handler Not Found'

---

README.md
build.gradle

https://tools.hmcts.net/jira/browse/DMP-5055
Move from Jitpack to Azure Devops Artifacts
```
[ ] Yes
[ x] No
```

DMP-5055 Move from Jitpack to Azure Devops Artifacts

---

build.gradle

https://tools.hmcts.net/jira/browse/DMP-5055
```
[ ] Yes
[ ] No
```

DMP-5055 Always use the latest release of darts-api openapi specs

---

build.gradle

Reverts hmcts/darts-gateway#875 Unable to see progress of master branch on jenkins

Revert "Update dependency org.bouncycastle:bcpkix-jdk18on to v1.82"
